# Generated by Django 5.1.6 on 2025-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='length',
            field=models.FloatField(default=0, verbose_name='Length'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='width',
            field=models.FloatField(default=0, verbose_name='Width'),
            preserve_default=False,
        ),
    ]
