# Generated by Django 5.1.6 on 2025-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='no_of_classes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='total_area_of_classes',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
