# Generated by Django 5.1.6 on 2025-03-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_no_of_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.CharField(max_length=30),
        ),
    ]
